Changed exit responsibility

diff --git a/servers b/servers
--- a/servers
+++ b/servers
@@ -1,4 +1,8 @@
 #!/bin/bash
+#
+## TODO: Make checking functions handle exits on error
+#
+
 SESSION="servers"
 MINECRAFT_WND="minecraft"
 DSTARVE_WND="dontstarve"
@@ -11,66 +15,80 @@ DSTARVE_CMD="$DSTARVE_DIR/start_dst.sh"
 
 RETURN_STATUS=0
 
-checkTmuxSession() 
+checkTmuxRunning() 
 {
     tmux has-session -t $SESSION > /dev/null 2>&1
-    let RETURN_STATUS=$?
+
+    if [ $? -eq 0 ]
+    then
+        echo "Tmux session already running"
+        exit 1
+    fi
+}
+
+checkTmuxNotRunning() 
+{
+    tmux has-session -t $SESSION > /dev/null 2>&1
+
+    if [ $? -eq 1 ]
+    then
+        echo "Tmux session not running. Try servers setup."
+        exit 1
+    fi
 }
 
 initTmux ()
 {
-    checkTmuxSession
-    if [ $RETURN_STATUS -eq 1 ]
-    then
-        local OLD_PWD=$PWD
-        # Change directory to where we want to land in the first window
-        # Rename the window to something useful
-        cd "$MINECRAFT_DIR" 
-        tmux new-session -d -s $1 
-        tmux rename-window -t0 $2
+    local OLD_PWD=$PWD
+    # Change directory to where we want to land in the first window
+    # Rename the window to something useful
+    cd "$MINECRAFT_DIR" 
+    tmux new-session -d -s $1 
+    tmux rename-window -t $SESSION:0 $2
 
-        # Change directory to where we want to land in the second window
-        # Create the window with a useful name
-        cd "$DSTARVE_DIR"
-        tmux new-window -d -n $3
-        cd $OLD_PWD 
+    # Change directory to where we want to land in the second window
+    # Create the window with a useful name
+    cd "$DSTARVE_DIR"
+    tmux new-window -da
+    tmux rename-window -t $SESSION:1 $3
+    cd $OLD_PWD 
 
-        echo "Created tmux session"
-    else
-        echo "Tmux session already running"
-    fi
+    echo "Created tmux session"
 }
 
 checkMinecraftRunning ()
 {
-    pgrep java
-    let RETURN_STATUS=$?
+    pgrep java > /dev/null 2>&1
+
+    if [ $? -eq 0 ]
+    then
+        echo "Minecraft is running"
+        exit 1
+    fi
+}
+
+checkMinecraftNotRunning()
+{
+    pgrep java > /dev/null 2>&1
+
+    if [ $? -eq 1 ]
+    then
+        echo "Minecraft is not running"
+        exit 1
+    fi
 }
 
 startMinecraft ()
 {
-    checkTmuxSession
-
-    if [ $RETURN_STATUS -eq 1 ]
-    then
-        echo "No session found. Try servers setup."
-        exit 1
-    fi
-
     checkMinecraftRunning
 
-    if [ $RETURN_STATUS -eq 1 ] 
-    then
-        tmux send-keys -t $SESSION:$MINECRAFT_WND "$MINECRAFT_CMD" Enter
-        echo "Starting minecraft..."
-    else
-        echo "Minecraft is already running"
-    fi
+    tmux send-keys -t $SESSION:$MINECRAFT_WND "$MINECRAFT_CMD" Enter
+    echo "Starting minecraft..."
 }
 
 stopMinecraft ()
 {
-    checkMinecraftRunning
+    checkMinecraftNotRunning
 
     if [ $RETRUN_STATUS -eq 0 ]
     then
@@ -125,12 +143,15 @@ attachSession ()
 
 case $1 in
     "setup")
+        checkTmuxRunning
         initTmux $SESSION $MINECRAFT_WND $DSTARVE_WND
         ;;
     "start")
+        checkTmuxNotRunning
         startServer $2
         ;; 
     "attach")
+        checkTmuxNotRunning
         attachSession $2
         ;;
     "help")
